[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/realms/master"
healthcheckTimeout = 600
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
name = "keycloak"
[http]
port = 8080
